version: "3.8"

services:
  web:
    build:
      context: .
    env_file:
      - ./env/.env.localhost
    environment:
      hellooktaapiclient_baseUrl: http://host.docker.internal:8070
    ports:
      - "8060:8060"
