server:
  port: 8070

logging:
  level:
    org.springframework.security.oauth2.client.OAuth2RestTemplate: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

csrf:
  csrf-enabled: true

spring:
  config:
    import: secrets.yml