hellooktaapi:
  security-mapping:
    ALLOWED_USERS:
      - HelloOkta_StandardUser
  filterOrderMapping:
    COMMONS_REQUEST_LOGGING: -10
    USER_LOGGING: 10


spring:
  main.allow-bean-definition-overriding: true
  application:
    name: hello-okta-api
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: ${issuer}
            authorization-uri: ${issuer}/v1/authorize
            token-uri: ${issuer}/v1/token
            user-info-uri: ${issuer}/v1/userinfo
            jwk-set-uri: ${issuer}/v1/keys
            user-name-attribute: email
      resourceserver:
        jwt:
          issuer-uri: ${issuer}
          jwk-set-uri: ${issuer}/v1/keys

logging:
  level:
    org.springframework.security.oauth2.client.OAuth2RestTemplate: ${rest_template_log_level:INFO}
    org.springframework.web.client.RestTemplate: ${rest_template_log_level:INFO}
    org.springframework.web.filter.CommonsRequestLoggingFilter: ${http_log_level:INFO}

schedule:
  jwk-set-cache-refresh-time: ${jwk_set_cache_refresh_time:300000} # 5 minutes