hellooktaapi:
  security-mapping:
    ALLOWED_USERS:
      - HelloOkta_StandardUser

okta:
  oauth2:
    issuer: ${issuer}
    clientId: ${clientId}
    clientSecret: ${clientSecret}
    audience: ${audience}

spring:
  main.allow-bean-definition-overriding: true
  application:
    name: hello-okta-api
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${clientId}
            client-secret: ${clientSecret}
        provider:
          okta:
            user-name-attribute: email

logging:
  level:
    org.springframework.security.oauth2.client.OAuth2RestTemplate: ${rest_template_log_level:INFO}
    org.springframework.web.client.RestTemplate: ${rest_template_log_level:INFO}
    org.springframework.web.filter.CommonsRequestLoggingFilter: ${http_log_level:INFO}
