server:
  port: 8070

logging:
  level:
    org.springframework.security.oauth2.client.OAuth2RestTemplate: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    lv.gennadyyonov.hellookta.services.UserInfoService: DEBUG

csrf:
  csrf-enabled: true

technical-endpoint:
  enabled: true

springdoc:
  swagger-ui:
    enabled: true

spring:
  config:
    import: secrets.yml