trigger: none

variables:
  tag: '$(Build.BuildId)'
  apiRepository: 'hellooktaapi'
  bffRepository: 'hellooktabff'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  displayName: 'Gradle Clean Build'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'clean build'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false

- task: Docker@2
  displayName: 'Docker Build API'
  inputs:
    containerRegistry: $(DockerServiceConnectionName)
    repository: $(apiRepository)
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/hello-okta-api/Dockerfile'
    tags: |
      $(tag)

- task: Docker@2
  displayName: 'Docker Build BFF'
  inputs:
    containerRegistry: $(DockerServiceConnectionName)
    repository: $(bffRepository)
    command: 'buildAndPush'
    Dockerfile: '$(Build.SourcesDirectory)/hello-okta-bff/Dockerfile'
    tags: |
      $(tag)