imagePullSecrets: []
nameOverride:
fullnameOverride:

serviceAccount:
  create: true
  annotations: {}
  name: "hellookta"

podSecurityContext: {}

securityContext: {}

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx,
    cert-manager.io/cluster-issuer: "selfsigned-issuer"
  }
  domain: "kubernetes.docker.internal"
  tls:
    secretName: "hello-okta-tls-cert"

api:
  port: 80
  replicaCount: 1
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources:
    limits:
      cpu: 384m
      memory: 0.5Gi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 8080
  image:
    repository: "localhost:5000/hellooktaapi"
    pullPolicy: Always
    tag: "latest"
  env:
    SERVER_SERVLET_CONTEXT_PATH: "/api"
    SPRING_PROFILES_ACTIVE: "dev,actuator"
    CSRF_CSRF_ENABLED: "false"
    TECHNICAL_ENDPOINT_ENABLED: "true"
    SPRINGDOC_SWAGGER_UI_ENABLED: "true"

bff:
  port: 80
  replicaCount: 1
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources:
    limits:
      cpu: 384m
      memory: 0.5Gi
    requests:
      cpu: 100m
      memory: 128Mi
  service:
    type: ClusterIP
    port: 8080
  image:
    repository: "localhost:5000/hellooktabff"
    pullPolicy: Always
    tag: "latest"
  env:
    SERVER_SERVLET_CONTEXT_PATH: "/bff"
    SPRING_PROFILES_ACTIVE: "dev,actuator"
    HEADERS_CSP_DIRECTIVES: "default-src 'self'; script-src 'self'; connect-src 'self' *.okta.com; img-src 'self' *.oktacdn.com data: blob:; frame-src 'self' *.okta.com; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'self'; font-src 'self' *.oktacdn.com; manifest-src 'self'; media-src 'self'; worker-src 'none';"
    CORS_ALLOWED_ORIGINS: "https://dev-220281.okta.com"
    CHUCK_NORRIS_URL: "https://api.chucknorris.io"
    CSRF_CSRF_ENABLED: "false"
    TECHNICAL_ENDPOINT_ENABLED: "true"
    SPRINGDOC_SWAGGER_UI_ENABLED: "true"
    GRAPHQL_TOOLS_INTROSPECTION_ENABLED: "true"
    GRAPHIQL_ENABLED: "true"
    VOYAGER_ENABLED: "true"
    GRAPHQL_PLAYGROUND_ENABLED: "true"
    ALTAIR_ENABLED: "true"

spa:
  port: 80
  replicaCount: 1
  podAnnotations: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources:
    limits:
      cpu: "250m"
      memory: "128Mi"
    requests:
      cpu: "25m"
      memory: "64Mi"
  service:
    type: ClusterIP
    port: 80
  image:
    repository: "localhost:5000/hellooktaspa"
    pullPolicy: Always
    tag: "latest"
  env:
    CSPHEADER: "default-src 'self'; script-src 'self'; connect-src 'self' *.okta.com; img-src 'self' *.oktacdn.com data: blob:; frame-src 'self' *.okta.com; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'self'; font-src 'self' *.oktacdn.com; manifest-src 'self'; media-src 'self'; worker-src 'none';"