replicaCount: 1

imagePullSecrets: []
nameOverride:
fullnameOverride:

serviceAccount:
  create: true
  annotations: {}
  name: "hellookta"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
  domain: "kubernetes.docker.internal"
  tls: []

resources:
  limits:
    cpu: 384m
    memory: 0.5Gi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

api:
  service:
    type: ClusterIP
    port: 80
  image:
    repository: "localhost:5000/hellooktaapi"
    pullPolicy: Always
    tag: "latest"
  env:
    "server.port": 80
    "server.servlet.context-path": "/api"
    "spring.profiles.active": "localhost,actuator"
    "issuer": "https://dev-220281.okta.com/oauth2/aus26efk9hrb1yASy357"
    "spring.security.oauth2.client.registration.okta.client-id": "0oa4yt76r3KSPx094357"
    "okta.oauth2.clientId": "0oa4yt76r3KSPx094357"
    "audience": "api://hellookta"
    "rest_template_log_level": "DEBUG"