replicaCount: 1

imagePullSecrets: []
nameOverride:
fullnameOverride:

serviceAccount:
  create: true
  annotations: {}
  name: "hellookta"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

ingress:
  enabled: true
  annotations: {
    kubernetes.io/ingress.class: nginx
  }
  domain: "kubernetes.docker.internal"
  tls: []

resources:
  limits:
    cpu: 384m
    memory: 0.5Gi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

api:
  service:
    type: ClusterIP
    port: 80
  image:
    repository: "localhost:5000/hellooktaapi"
    pullPolicy: Always
    tag: "latest"
  env:
    SERVER_PORT: 80
    SERVER_SERVLET_CONTEXT_PATH: "/api"
    SPRING_PROFILES_ACTIVE: "actuator"
    ISSUER: "https://dev-220281.okta.com/oauth2/aus26efk9hrb1yASy357"
    SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OKTA_CLIENT_ID: "0oa4yt76r3KSPx094357"
    AUDIENCE: "api://hellookta"
    REST_TEMPLATE_LOG_LEVEL: "DEBUG"