# Docs: https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html

### Message

< scripts/csrf-token.js

POST {{api-host}}/hello
Content-Type: application/json
Authorization: {{okta-token-type}} {{okta-access-token}}
Cookie: XSRF-TOKEN={{csrf-token}}
X-XSRF-TOKEN: {{csrf-token}}

###