### Environment

GET {{bff-host}}/config/environment

> {%
  if (response.status === 200) {
      var oktaIssuer = response.body.oktaIssuer;
      client.global.set('okta-issuer', oktaIssuer);
      client.log('Environment Configuration successfully saved');
  }
%}

### Get Access Token

POST {{okta-issuer}}/v1/token
Content-Type: application/x-www-form-urlencoded
Accept: application/json

grant_type=client_credentials&client_id={{okta-run-as-client-id}}&client_secret={{okta-run-as-client-secret}}&scope=message.read

> {%
  if (response.status === 200) {
      var tokenType = response.body.token_type;
      var accessToken = response.body.access_token;
      client.global.set('okta-token-type', tokenType);
      client.global.set('okta-access-token', accessToken);
      client.log('Access Token successfully saved');
  }
%}

###