# Docs: https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html

### Request bodies are taken from localhost SPA environment, Developer Tools Network Params tab

### User Profile

< scripts/csrf-token.js

POST {{bff-host}}/graphql
Authorization: {{okta-token-type}} {{okta-access-token}}
Cookie: XSRF-TOKEN={{csrf-token}}
X-XSRF-TOKEN: {{csrf-token}}
Content-Type: application/json

< ./requests/me.json

### Translation Map

< scripts/csrf-token.js

GET {{bff-host}}/translationmap
Authorization: {{okta-token-type}} {{okta-access-token}}
Cookie: XSRF-TOKEN={{csrf-token}}
X-XSRF-TOKEN: {{csrf-token}}
Content-Type: application/json

### Hello

< scripts/csrf-token.js

POST {{bff-host}}/graphql
Authorization: {{okta-token-type}} {{okta-access-token}}
Cookie: XSRF-TOKEN={{csrf-token}}
X-XSRF-TOKEN: {{csrf-token}}
Content-Type: application/json

< ./requests/hello.json

### Ping

< scripts/csrf-token.js

POST {{bff-host}}/graphql
Authorization: {{okta-token-type}} {{okta-access-token}}
Cookie: XSRF-TOKEN={{csrf-token}}
X-XSRF-TOKEN: {{csrf-token}}
Content-Type: application/json

< ./requests/ping.json

###