management:
  endpoint:
    health:
      showDetails: always
    loggers:
      enabled: true
  endpoints:
    enabledByDefault: true
    web:
      exposure:
        include: ${management_endpoints_web_exposure_include:info,health,loggers,metrics,auditevents,httpexchanges,prometheus}
  metrics:
    export:
      prometheus:
        enabled: true

info:
  app:
    encoding: UTF-8
    java:
      source: 15
      target: 15
