management:
  endpoints:
    web:
      exposure:
        include: "${management_endpoints_web_exposure_include:info, health, metrics, auditevents, httptrace, prometheus}"

info:
  app:
    encoding: UTF-8
    java:
      source: 15
      target: 15

