management:
  endpoint:
    health:
      showDetails: always
    loggers:
      access: read-only
  endpoints:
    access:
      default: read_only
    web:
      exposure:
        include: ${management_endpoints_web_exposure_include:info,health,loggers,metrics,auditevents,httpexchanges,prometheus}
  prometheus:
    metrics:
      export:
        enabled: true
  info:
    env:
      enabled: true

info:
  app:
    encoding: UTF-8
    java:
      source: 21
      target: 21
