management:
  endpoints:
    web:
      exposure:
        include: "${management_endpoints_web_exposure_include:info, health, metrics, auditevents, httptrace}"

info:
  app:
    encoding: UTF-8
    java:
      source: 1.8
      target: 1.8

