apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hello-okta-bff.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "hello-okta-bff.name" . }}
    helm.sh/chart: {{ include "hello-okta.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ include "hello-okta-bff.name" . }}
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.bff.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "hello-okta-bff.name" . }}
  template:
    metadata:
      {{- with .Values.bff.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "hello-okta-bff.name" . }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hello-okta.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "hello-okta-bff.name" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.bff.image.repository }}:{{ .Values.bff.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.bff.image.pullPolicy }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.bff.service.port }}"
            - name: HELLOOKTAAPICLIENT_BASEURL
              value: {{ include "hello-okta-api.dns" . }}
          {{- range $key, $value := .Values.bff.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
          {{- end }}
          ports:
            - name: http-bff
              containerPort: {{ .Values.bff.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.bff.resources | nindent 12 }}
      {{- with .Values.bff.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bff.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bff.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
