{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "hello-okta.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "hello-okta.name" . }}
    helm.sh/chart: {{ include "hello-okta.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    - host: {{ include "hello-okta.domainName" . }}
      http:
        paths:
          - path: {{ .Values.api.env.SERVER_SERVLET_CONTEXT_PATH }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "hello-okta-api.name" . }}
                port:
                  number: {{ .Values.api.port }}
          - path: {{ .Values.bff.env.SERVER_SERVLET_CONTEXT_PATH }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "hello-okta-bff.name" . }}
                port:
                  number: {{ .Values.bff.port }}
  {{- end }}
