server:
  port: 8060

management:
  server:
    port: 8012
  endpoints:
    security:
      enabled: true
      allowedRoles:
        - APPLICATION_MONITOR
    proxy:
      enabled: true
      path: /proxy/actuator
      url: http://localhost:${management.server.port}/actuator

headers:
  csp:
    directives: "default-src 'self'; script-src 'self'; connect-src 'self' localhost:* *.okta.com; img-src 'self' *.oktacdn.com data: blob:; frame-src 'self' *.okta.com; style-src 'self' 'unsafe-inline'; object-src 'none'; base-uri 'self'; font-src 'self' *.oktacdn.com; manifest-src 'self'; media-src 'self'; worker-src 'none';"

chuck-norris:
  url: https://api.chucknorris.io

hello-okta-api:
  url: http://localhost:8070/api

logging:
  level:
    org.springframework.security.oauth2.client.OAuth2RestTemplate: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    lv.gennadyyonov.hellookta.services.UserInfoService: DEBUG

csrf:
  csrf-enabled: true

technical-endpoint:
  enabled: true

springdoc:
  swagger-ui:
    enabled: true

spring:
  graphql:
    schema:
      introspection:
        enabled: true
    graphiql:
      enabled: true
  config:
    import: secrets.yml
