hellooktabff:
  security-mapping:
    ALLOWED_USERS:
      - HelloOkta_StandardUser

okta:
  oauth2:
    issuer: ${issuer}
    clientId: ${clientId}
    clientSecret: ${clientSecret}
    audience: ${audience}

spring:
  main.allow-bean-definition-overriding: true
  application:
    name: hello-okta-bff
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: ${clientId}
            client-secret: ${clientSecret}
        provider:
          okta:
            user-name-attribute: email

hellooktaapiclient:
  baseUrl: ${hellooktaapiclient_baseUrl}
  runAsDetails:
      grantType: client_credentials
      clientId: ${hellooktaclient_id}
      clientSecret: ${hellooktaclient_secret}
      accessTokenUri: ${issuer}/v1/token
      scope: message.read

logging:
  level:
    org.springframework.security.oauth2.client.OAuth2RestTemplate: ${rest_template_log_level:INFO}
    org.springframework.web.client.RestTemplate: ${rest_template_log_level:INFO}
    lv.gennadyyonov.hellookta.bff.connectors.hellooktaapi.HelloOktaApiConnector: ${hello_okta_api_log_level:INFO}
    lv.gennadyyonov.hellookta.bff.connectors.okta.TokenConnector: ${okta_token_log_level:INFO}
    org.springframework.web.filter.CommonsRequestLoggingFilter: ${http_log_level:INFO}
